<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ6we23U\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ6we23U/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ6we23U.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ6we23U\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ6we23U\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q6we23U',
    'container.build_id' => '66c44cbe',
    'container.build_time' => 1623144116,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ6we23U');
