<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHygvPbq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHygvPbq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHygvPbq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHygvPbq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHygvPbq\App_KernelDevDebugContainer([
    'container.build_hash' => 'HygvPbq',
    'container.build_id' => '1d712f63',
    'container.build_time' => 1617961556,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHygvPbq');
