<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '3f461ff0fc99bd513233360ab92c4bed',
  'DATABASE_URL' => 'mysql://root:adminbeel@127.0.0.1:3306/quizz?serverVersion=13&charset=utf8',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
);
