<?php

namespace ContainerLcyjh1O;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuizzControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\QuizzController' shared autowired service.
     *
     * @return \App\Controller\QuizzController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\QuizzController'] = $instance = new \App\Controller\QuizzController(($container->privates['App\\Repository\\QuizzRepository'] ?? $container->load('getQuizzRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->load('get_ServiceLocator_5nX7ca3Service'))->withContext('App\\Controller\\QuizzController', $container));

        return $instance;
    }
}
