<?php

namespace ContainerLcyjh1O;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScoreRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ScoreRepository' shared autowired service.
     *
     * @return \App\Repository\ScoreRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ScoreRepository'] = new \App\Repository\ScoreRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
