api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    title: 'REST API du projet Quizz'
    description: 'A Symfony API to manage quizz application.'
    version: '1.0.0'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
